In [1]:
import numpy as np
import random

a = np.array([x+12 for x in range(12)])
print(a)

[12 13 14 15 16 17 18 19 20 21 22 23]


In [2]:
b1 = np.resize(a, (5, 2))
print(b1)

[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]]


In [3]:
b2 = np.reshape(a, (6, -1))
print(b2)

[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]


In [4]:
b3 = np.reshape(a, (-1, 3))
print(b3)

[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]


4. Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?


Да

5. Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [8]:
a = np.reshape(np.array([random.uniform(-1.0, 1.0) for x in range(12)]), (3, 4))
print(a)
b = np.resize(a, (1, 4))
print(b)

[[-0.71373827 -0.20978397 -0.62934117 -0.79103888]
 [-0.72163627  0.77996593 -0.77185445 -0.07400185]
 [ 0.52820645  0.96485097  0.05619759 -0.46023733]]
[[-0.71373827 -0.20978397 -0.62934117 -0.79103888]]


6. Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2. Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?

In [12]:
a = np.array([20 - x*2 for x in range(10)])
print(a)
b = np.array([20 - x*2 for x in range(10)])
print(b)

print(np.array_equal(a, b))

[20 18 16 14 12 10  8  6  4  2]
[20 18 16 14 12 10  8  6  4  2]
True


7. Вертикально соединить массивы a и b. a — двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц.
Итоговый массив v должен иметь атрибут size, равный 10.